### ISSUE TITLE
perf_to_profile: [ERROR:perf_data_handler.cc:310] stat: missing_callchain_mmap 20547/294830

### ISSUE THREAD

**Issue by tamird** [google/perf_data_converter#40]
Triggered when attempting to convert a perf capture of an OCaml program. Unfortunately, I can't share the code, but I might be able to produce a freestanding reproduction case if someone's available to chase this.

**Comment by aalexand** [comment]
@lannadorai PTAL, but I think these are benign in most cases. We should probably downgrade the logging severity?

**Comment by tamird** [comment]
Doing this again with file generated with `perf record --call-graph dwarf` produces a fatal error:
```
[ERROR:perf_data_converter.cc:659] Could not read input perf.data
Expected profile vector to have one element.
Aborted
```

**Comment by lannadorai** [comment]
@tamird Could you please share the perf.data files for both the cases?

**Comment by tamird** [comment]
I can't share them publicly - could you email me directly? My email is
listed on my profile.

**Comment by lannadorai** [comment]
Below is the complete error log from perf_to_profile to convert a perf.data file generated with `perf record --call-graph dwarf`:

[ERROR:quipper/sample_info_reader.cc:275] PERF_SAMPLE_REGS_USER is not yet supported.
[ERROR:quipper/sample_info_reader.cc:519] Read/skipped 184 bytes, expected 8568 bytes.
[ERROR:perf_data_converter.cc:659] Could not read input perf.data
Expected profile vector to have one element.
Aborted

It looks that quipper doesn't support PERF_SAMPLE_REGS_USER sample type. So, it fails to process perf.data containing this sample type.

Patches are welcome to add support for this sample type. We do not accept pull request because of the hassle of merging it with the upstream. However, you could add a link to a patch in this issue.

**Comment by aalexand** [comment]
I am closing this issue because the original report which is error messages about addresses from the call stack not being within in mmap'ed regions was fixed by making that error message a warning. As for further comments in this discussion about the converter complaining about PERF_SAMPLE_REGS_USER and PERF_SAMPLE_STACK_USER types, I believe there is a way to make sure the perf.data file doesn't contain the data so I'd recommend trying that. Please comment further / re-open if there are still issues that can't be worked around easily.
